Last call PR
scheme-requests-for-implementation/srfi-170 pull request #12
Opened 2020-06-23 16:02 UTC by johnwcowan

2020-06-23 17:01 UTC, hga commented
Note, this pull request does not include changes to the Chibi Scheme sample implementation, which I'm working on right now, should not take long to complete.

2020-06-23 19:22 UTC, hga commented
The Chibi Scheme sample implementation is finished, and checked into https://github.com/hga/srfi-170

2020-06-23 19:24 UTC, arthurgleckler requested changes
Whatever gave you the idea that Olin Shivers had died — and in 1995?  I have email from his as recently as May, and I've heard no news of his passing.  And he certainly wasn't born in 1924.

Or is this some Shiversian practical joke?

2020-06-24 19:40 UTC, arthurgleckler approved these changes

2020-06-24 22:00 UTC, merged